import type { FleetSnapshot } from './model.ts'

export const fixtureSnapshot: FleetSnapshot = {
  provenance: {
    mode: 'fixture',
    label: 'Tracked demonstration fixture',
    observedAt: '2026-08-07T10:00:00Z',
    sourceContract: 'Fixture mirrors fm-fleet-snapshot.v1; no live commands were run.',
  },
  trust: {
    bind: '127.0.0.1',
    transport: 'tailscale-private',
    authentication: 'Tailnet identity plus an app session is required in live mode.',
    cloudflare: 'not-configured',
    tailscale: 'available',
    thinkpad: 'unavailable',
    capabilities: { planMutation: false, sendInstruction: false, documentWrite: false },
  },
  workers: [
    {
      id: 'firstmate-control-plane-ui-20260810',
      title: 'Build operator control plane',
      project: 'firstmate',
      kind: 'ship',
      state: 'working',
      stateSource: 'pane',
      backend: 'herdr',
      endpoint: 'fm-lab:firstmate-control-plane-pane',
      harness: 'codex',
      lastEvent: 'Implementation under way',
    },
    {
      id: 'thinkpad-unity-review',
      title: 'Review Unity work on ThinkPad',
      project: 'game-prototype',
      kind: 'scout',
      state: 'blocked',
      stateSource: 'remote-route',
      backend: 'herdr',
      endpoint: 'thinkpad-visible:unity-pane',
      harness: 'claude',
      blocker: 'Visible ThinkPad Herdr session is unavailable.',
      remote: { host: 'fm-thinkpad', visibility: 'unavailable' },
    },
    {
      id: 'docs-safety-review',
      title: 'Review document redaction boundary',
      project: 'firstmate',
      kind: 'scout',
      state: 'parked',
      stateSource: 'status-log',
      backend: 'tmux',
      endpoint: 'fm:fm-docs-safety-review',
      harness: 'codex',
      lastEvent: 'Awaiting captain decision',
    },
  ],
  secondmates: [
    {
      id: 'product',
      summary: 'Product implementation and release planning',
      scope: 'Product features, UI delivery, and release readiness.',
      projects: ['firstmate', 'operator-ui'],
      state: 'working',
      remote: false,
      home: '/firstmate-homes/product',
      activeChildren: 1,
      queued: 2,
      decisions: 1,
      availability: 'ready',
    },
    {
      id: 'thinkpad',
      summary: 'Visible workstation tasks',
      scope: 'Windows, Chrome, and Unity work requiring the ThinkPad display.',
      projects: ['game-prototype'],
      state: 'unknown',
      remote: true,
      host: 'fm-thinkpad',
      home: '/home/devuser/firstmate-thinkpad',
      activeChildren: 0,
      queued: 1,
      decisions: 0,
      availability: 'unavailable',
      reason: 'No exact visible Herdr workspace and pane could be verified.',
    },
  ],
  decisions: [
    {
      key: 'docs-safety-review/allowed-write-surface',
      title: 'Choose the first bounded document write owner',
      origin: 'docs-safety-review',
      reason: 'Direct filesystem writes would bypass an existing authority contract.',
      blockedWork: ['Document editing'],
    },
  ],
  documents: [
    {
      id: 'operator-architecture',
      title: 'Operator control-plane architecture',
      path: 'docs/operator-control-plane.md',
      kind: 'architecture',
      updatedAt: '2026-08-07T09:40:00Z',
      provenance: 'Tracked maintainer architecture fixture',
      content: '# Operator boundary\n\nThe web layer reads the stable fleet snapshot and never becomes a task database.\n\nToken: [REDACTED]',
      redactions: 1,
      writable: false,
      writeReason: 'No audited document write adapter is enabled.',
    },
    {
      id: 'docs-safety-review',
      title: 'Document safety review',
      path: 'data/docs-safety-review/report.md',
      kind: 'report',
      updatedAt: '2026-08-07T09:25:00Z',
      provenance: 'Bounded scout report fixture',
      content: '# Findings\n\nOnly report pointers from the authoritative snapshot are readable. Secret-shaped values are redacted before delivery.',
      redactions: 0,
      writable: false,
      writeReason: 'Report mutation remains owned by the task lifecycle.',
    },
  ],
  skills: [
    {
      id: 'firstmate:bearings',
      name: 'bearings',
      description: 'Build a bounded fleet status digest from authoritative state.',
      appliesTo: 'Captain catch-up and current fleet status.',
      source: 'Firstmate built-in',
      path: '.agents/skills/bearings/SKILL.md',
      invocation: '/bearings',
      invocationNote: 'Invoke in the Firstmate conversation.',
      userInvocable: true,
    },
    {
      id: 'firstmate:stow',
      name: 'stow',
      description: 'Route durable session knowledge before a context reset.',
      appliesTo: 'Firstmate session handoff.',
      source: 'Firstmate built-in',
      path: '.agents/skills/stow/SKILL.md',
      invocation: '/stow',
      invocationNote: 'Invoke in the Firstmate conversation.',
      userInvocable: true,
    },
    {
      id: 'installed:design-taste-frontend',
      name: 'design-taste-frontend',
      description: 'Design and polish distinctive frontend interfaces.',
      appliesTo: 'Frontend visual systems and implementation.',
      source: 'Installed skill root (example)',
      path: '$CODEX_HOME/skills/design-taste-frontend/SKILL.md',
      invocation: '$design-taste-frontend',
      invocationNote: 'Invoke explicitly in a compatible Codex surface.',
      userInvocable: true,
    },
    {
      id: 'firstmate:harness-adapters',
      name: 'harness-adapters',
      description: 'Own verified harness launch and control behavior.',
      appliesTo: 'Agent runtime only.',
      source: 'Firstmate internal',
      path: '.agents/skills/harness-adapters/SKILL.md',
      invocation: null,
      invocationNote: 'Agent-only. Loaded by its documented trigger.',
      userInvocable: false,
    },
  ],
  blockers: [
    'ThinkPad visible Herdr is unavailable; remote UI actions refuse fallback.',
    'Mutation capabilities are disabled in this test-only fixture.',
  ],
}
